{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "oracle-instantclient.serviceAccountName" . }}
  labels:
{{ include "oracle-instantclient.labels" . | nindent 4 }}
{{- end -}}
